export const SET_TOP_BAKERS_BY_STAKE = 'SET_TOP_BAKERS_BY_STAKE';
export const SET_TOP_BAKERS_BY_BLOCK = 'SET_TOP_BAKERS_BY_BLOCK';
export const SET_TOP_BAKERS_BY_DELEGATION = 'SET_TOP_BAKERS_BY_DELEGATION';
export const SET_TOP_BAKERS_BY_STAKE_LOADING = 'SET_TOP_BAKERS_BY_STAKE_LOADING';
export const SET_TOP_BAKERS_BY_DELEGATION_LOADING = 'SET_TOP_BAKERS_BY_DELEGATION_LOADING';
export const SET_TOP_BAKERS_BY_BLOCK_LOADING = 'SET_TOP_BAKERS_BY_BLOCK_LOADING';
