export const SET_TOP_CONTRACTS_BY_BALANCE = 'SET_TOP_CONTRACTS_BY_BALANCE';
export const SET_TOP_CONTRACTS_BY_BALANCE_LOADING = 'SET_TOP_CONTRACTS_BY_BALANCE_LOADING';
export const SET_TOP_CONTRACTS_BY_INVOCATION = 'SET_TOP_CONTRACTS_BY_INVOCATION';
export const SET_TOP_CONTRACTS_BY_INVOCATION_LOADING = 'SET_TOP_CONTRACTS_BY_INVOCATION_LOADING';