export const SET_HOURLY_VOLUME = 'SET_HOURLY_VOLUME';
export const SET_HOURLY_VOLUME_LOADING ='SET_HOURLY_VOLUME_LOADING';

export const SET_HOURLY_GAS = 'SET_HOURLY_GAS';
export const SET_HOURLY_GAS_LOADING ='SET_HOURLY_GAS_LOADING';

export const SET_HOURLY_FEE = 'SET_HOURLY_FEE';
export const SET_HOURLY_FEE_LOADING ='SET_HOURLY_FEE_LOADING';

export const SET_DAILY_ACTIVATION = 'SET_DAILY_ACTIVATION';
export const SET_DAILY_ACTIVATION_LOADING ='SET_DAILY_ACTIVATION_LOADING';

export const SET_DAILY_ORIGINATION = 'SET_DAILY_ORIGINATION';
export const SET_DAILY_ORIGINATION_LOADING ='SET_DAILY_ORIGINATION_LOADING';